//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDHLee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public Nullable<bool> Publish { get; set; }
        public Nullable<int> BlogId { get; set; }

        [Required(ErrorMessage = "Name required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Email required (don't worry we won't share this is anyone)")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
