//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HDHDBContext : DbContext
    {
        public HDHDBContext()
            : base("name=HDHDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminEvent> AdminEvents { get; set; }
        public DbSet<Donation> Donations { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<EventUser> EventUsers { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<FAQ> FAQs { get; set; }
        public DbSet<FeedBack> FeedBacks { get; set; }
        public DbSet<Parking> Parkings { get; set; }
        public DbSet<NewsLetter> NewsLetters { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Worker> Workers { get; set; }
        public DbSet<tblDoctor> tblDoctors { get; set; }
        public DbSet<tblDonation> tblDonations { get; set; }
        public DbSet<tblFAQ> tblFAQs { get; set; }
    }
}
