//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public string Department { get; set; }
        public string Shift { get; set; }
        public string FT_PT { get; set; }
        public Nullable<decimal> Pay { get; set; }
        public string Description { get; set; }
        public string Resume { get; set; }
    }
}
