//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDonation
    {
        public int DonationId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Regdate { get; set; }
    }
}
