//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorker
    {
        public int Id { get; set; }
        public string jobTitle { get; set; }
        public string location { get; set; }
        public string email { get; set; }
        public string shift { get; set; }
        public Nullable<int> pay { get; set; }
        public string desciption { get; set; }
    }
}
