//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Appointment
    {
        [Key]
        public int Id { get; set; }
        [DisplayName("First name")]
        [Required(ErrorMessage = "Please enter your first name.")]
        [RegularExpression(@"^([ \u00c0-\u01ffa-zA-Z'\-])+$", ErrorMessage = "Please enter upper and lower case alphabets only.")]
        public string Firstname { get; set; }
        [DisplayName("Last name")]
        [Required(ErrorMessage = "Please enter your last name.")]
        [RegularExpression(@"^([ \u00c0-\u01ffa-zA-Z'\-])+$", ErrorMessage = "Please enter upper and lower case alphabets only.")]
        public string Lastname { get; set; }
        [Required(ErrorMessage = "Please enter your birth date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Birth Date")]
        public Nullable<System.DateTime> BirthDate { get; set; }
        [Required(ErrorMessage = "Please enter your email address.")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Email Address")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter your phone number.")]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Phone number")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid phone number.")]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Please select your preferred date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayName("Preferred Date")]
        public Nullable<System.DateTime> PreferredDate { get; set; }
        [Required(ErrorMessage = "Please select your preferred time.")]
        [DataType(DataType.Time)]
        [DisplayName("Preferred Time")]
        public Nullable<System.TimeSpan> PreferredTime { get; set; }
        public string Description { get; set; }
        [Required(ErrorMessage = "Please select your preferred service.")]
        [DisplayName("Preferred Service")]
        public Nullable<int> Service { get; set; }
        [Required(ErrorMessage = "Please select your preferred therapist.")]
        [DisplayName("Preferred Therapist")]
        public Nullable<int> Therapist { get; set; }
        [Required(ErrorMessage = "Please select a set status for this appointment.")]
        public string Set { get; set; }
    }
}
