//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int DonationId { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string Regularity { get; set; }
        public int CardNumber { get; set; }
        public int CVS { get; set; }
        public string ExpiryDate { get; set; }
        public string Email { get; set; }
    }
}
