//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HDHDBEntities : DbContext
    {
        public HDHDBEntities()
            : base("name=HDHDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminEvents> AdminEvents { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Donation> Donation { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<EventUsers> EventUsers { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<NewsLetters> NewsLetters { get; set; }
        public virtual DbSet<Parking> Parking { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
