//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotreDameHumber_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        public int ParkingId { get; set; }
        public string LocationTitle { get; set; }
        public string PaymentDetails { get; set; }
        public Nullable<System.TimeSpan> Hours { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}
